---
title: "Data visualization"
author: "Tess Scheidel"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tigris)
library(leaflet)
options(tigris_use_cache = TRUE)
```

## Leaflet Visualizations

```{r}

char_zips <- zctas(cb = TRUE, starts_with = zip_codes) %>% 
  geo_join(tbl, by_sp = "GEOID10", by_df = "zipcode", how = "left")

plot_var_by_zip <- function(var, subtitle) {
  
  measure <- char_zips %>% pluck(var)
  
  pal <- colorNumeric(
    palette = "Blues",
    domain = measure)

  if ( grepl("median", "var") ) {
    labels <- paste0(
      "Zip Code: ",
      char_zips$GEOID10, "<br/>",
      subtitle, ": ",
      scales::dollar(measure, scale = 1)) %>% # dollar sign
    lapply(htmltools::HTML)
  } else {
    labels <- paste0(
      "Zip Code: ",
      char_zips$GEOID10, "<br/>",
      subtitle, ": ",
      scales::percent(measure, scale = 1)) %>% # percent
    lapply(htmltools::HTML)
  }

  char_zips %>% 
    leaflet %>% 
    addProviderTiles("CartoDB") %>% 
    addPolygons(fillColor = ~pal(measure),
                weight = 2,
                opacity = 1,
                color = "white",
                dashArray = "3",
                fillOpacity = 0.7,
                highlight = highlightOptions(weight = 2,
                                             color = "#666",
                                             dashArray = "",
                                             fillOpacity = 0.7,
                                             bringToFront = TRUE),
                label = labels) %>%
    addLegend(pal = pal, 
              values = ~measure,
              opacity = 0.7, 
              title = htmltools::HTML(paste0(
                                      subtitle,
                                      " <br> 
                                      by Zip Code <br>
                                      2020")),
              position = "bottomright")
}

vars <- tbl %>% select(-zipcode) %>% colnames()
labels <- c("Percent Asian",
            "Percent Black",
            "Percent Diagnosed with COPD",
            "Percent Diagnosed with Depression",
            "Percent Diagnosed with Diabetes",
            "Percent Diagnosed with Heart Disease",
            "Percent Hispanic/Latino",
            "Median Income",
            "Life Expectancy at Birth",
            "Median Age",
            "Percent Am Indian/Alaskan Native",
            "Number of People with a Disability Living in Poverty",
            "Percent Native Hawaiian/Other Pacific",
            "Percent with 1 or More Disabilities",
            "Percent Foreign Born",
            "Percent Non-English (Age > 5)",
            "Percent Living in Poverty",
            "Percent Diagnosed with Having a Stroke",
            "Percent White",
            "Percent of the White Population Living In Poverty")

plot_var_by_zip(var      = vars[1],
                subtitle = labels[1])

plot_var_by_zip(var      = vars[2],
                subtitle = labels[2])

plot_var_by_zip(var      = vars[3],
                subtitle = labels[3])

plot_var_by_zip(var      = vars[4],
                subtitle = labels[4])

plot_var_by_zip(var      = vars[5],
                subtitle = labels[5])

plot_var_by_zip(var      = vars[6],
                subtitle = labels[6])

plot_var_by_zip(var      = vars[7],
                subtitle = labels[7])

plot_var_by_zip(var      = vars[8],
                subtitle = labels[8])

plot_var_by_zip(var      = vars[9],
                subtitle = labels[9])

plot_var_by_zip(var      = vars[10],
                subtitle = labels[10])

plot_var_by_zip(var      = vars[11],
                subtitle = labels[11])

plot_var_by_zip(var      = vars[12],
                subtitle = labels[12])

plot_var_by_zip(var      = vars[13],
                subtitle = labels[13])

plot_var_by_zip(var      = vars[14],
                subtitle = labels[14])

plot_var_by_zip(var      = vars[15],
                subtitle = labels[15])

plot_var_by_zip(var      = vars[16],
                subtitle = labels[16])

plot_var_by_zip(var      = vars[17],
                subtitle = labels[17])

plot_var_by_zip(var      = vars[18],
                subtitle = labels[18])

plot_var_by_zip(var      = vars[19],
                subtitle = labels[19])

plot_var_by_zip(var      = vars[20],
                subtitle = labels[20])

```

