---
title: "HNR 499 Project"
author: Tess Scheidel
output: 
  html_document: 
    df_print: kable
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tigris)
library(leaflet)
options(tigris_use_cache = TRUE)
```

Data was downloaded from PolicyMap Database (https://gvsu-policymap-com.ezproxy.gvsu.edu/maps)

## Data Cleaning

```{r read-clean, warning = FALSE}


read_clean_zip <- function(files, zip, summary) {
  
  quo(
    files %>% 
      keep(str_detect(., zip)) %>% 
      map(~ .x %>% 
            read_csv(show_col_types = FALSE, na = c("", "NA", "N/A")) %>%
            drop_na() %>%
            janitor::clean_names() %>% 
            mutate(zipcode = readr::parse_number(.x),
                   tract = row_number()) %>% 
            select(-c(1:3))) %>% 
      reduce(left_join, by = c("zipcode", "tract")) %>% 
      group_by(zipcode) %>% 
      summarize_all(!!sym(summary), na.rm = TRUE) %>% 
      select(-tract) 
  ) %>% 
    rlang::eval_tidy()
}

metric_files <- list.files("data/metrics", full.names = TRUE) 
metric_zip_codes    <- readr::parse_number(metric_files) %>% unique() %>% as.character()

metrics_tbl <- metric_zip_codes %>% 
  map_df(~read_clean_zip(files = metric_files, .x, summary = "mean")) %>% 
  mutate_if(is.numeric, round, 2) %>%
  mutate(zipcode = as.character(zipcode))

pop_files <- list.files("data/population", full.names = TRUE) 
pop_zip_codes    <- readr::parse_number(pop_files) %>% unique() %>% as.character()

pop_tbl <- pop_zip_codes %>% 
  map_df(~read_clean_zip(files = pop_files, .x, summary = "sum")) %>% 
  mutate_if(is.numeric, round, 2) %>%
  mutate(zipcode = as.character(zipcode))

tbl <- metrics_tbl %>% 
  left_join(pop_tbl, by = "zipcode")

write_csv(tbl, "kent_county_2020_data.csv")
```